server:
  error:
    whitelabel:
      enabled: true
  port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: INFO

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Tekka Api Documentation
    version: v1
  contact:
    name: Ant Kaynak
    url: https://www.keyist.tech
    email: tekken.ruw@gmail.com

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    host_address: host_address
    username: username
    password: password
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

  mvc:
    throw-exception-if-no-handler-found: true

  application:
    name: iT-shirt
  main:
    banner-mode: off

  datasource:
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source

  h2:
    console:
      enabled: true
      path: /h2

security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:8081/oauth/check_token
    client_id: client_id
    client_password: client_password
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**